package Controller;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/logservert")
public class LoggingServlet extends HttpServlet{
	
	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		
		//set content type
		resp.setContentType("text/html");
		PrintWriter out = resp.getWriter();
		
		out.print("<!DOCTYPE html>\r\n"
				+ "<html lang=\"en\">\r\n"
				+ "<head>\r\n"
				+ "<meta charset=\"UTF-8\">\r\n"
				+ "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "<title>Banking User Profile</title>\r\n"
				+ "<style>\r\n"
				+ "    body {\r\n"
				+ "        font-family: Arial, sans-serif;\r\n"
				+ "        background-color: #f4f4f4;\r\n"
				+ "        margin: 0;\r\n"
				+ "        padding: 0;\r\n"
				+ "    }\r\n"
				+ "    .container {\r\n"
				+ "        width: 500px;\r\n"
				+ "        margin: 50px auto;\r\n"
				+ "        background-color: #fff;\r\n"
				+ "        padding: 20px;\r\n"
				+ "        border-radius: 8px;\r\n"
				+ "        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n"
				+ "    }\r\n"
				+ "    h2 {\r\n"
				+ "        text-align: center;\r\n"
				+ "        margin-bottom: 20px;\r\n"
				+ "    }\r\n"
				+ "    .profile-info {\r\n"
				+ "        margin-bottom: 15px;\r\n"
				+ "    }\r\n"
				+ "    .profile-info label {\r\n"
				+ "        font-weight: bold;\r\n"
				+ "    }\r\n"
				+ "    .profile-info p {\r\n"
				+ "        margin: 5px 0;\r\n"
				+ "    }\r\n"
				+ "    .btn-container {\r\n"
				+ "        text-align: center;\r\n"
				+ "    }\r\n"
				+ "    .btn {\r\n"
				+ "        background-color: #4CAF50;\r\n"
				+ "        color: white;\r\n"
				+ "        padding: 10px 20px;\r\n"
				+ "        border: none;\r\n"
				+ "        border-radius: 4px;\r\n"
				+ "        cursor: pointer;\r\n"
				+ "        transition: background-color 0.3s ease;\r\n"
				+ "    }\r\n"
				+ "    .btn:hover {\r\n"
				+ "        background-color: #45a049;\r\n"
				+ "    }\r\n"
				+ "    .edit-profile-form {\r\n"
				+ "        display: none;\r\n"
				+ "    }\r\n"
				+ "    .edit-profile-form input {\r\n"
				+ "        width: calc(100% - 22px);\r\n"
				+ "        padding: 8px;\r\n"
				+ "        margin-bottom: 10px;\r\n"
				+ "        border: 1px solid #ccc;\r\n"
				+ "        border-radius: 4px;\r\n"
				+ "    }\r\n"
				+ "    .edit-profile-form .btn-container {\r\n"
				+ "        text-align: right;\r\n"
				+ "    }\r\n"
				+ "</style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "\r\n"
				+ "<div class=\"container\">\r\n"
				+ "    <h2>User Profile</h2>\r\n"
				+ "    <div class=\"profile-info\">\r\n"
				+ "        <label for=\"username\">Username:</label>\r\n"
				+ "        <p id=\"username\">JohnDoe123</p>\r\n"
				+ "    </div>\r\n"
				+ "    <div class=\"profile-info\">\r\n"
				+ "        <label for=\"fullname\">Full Name:</label>\r\n"
				+ "        <p id=\"fullname\">John Doe</p>\r\n"
				+ "    </div>\r\n"
				+ "    <div class=\"profile-info\">\r\n"
				+ "        <label for=\"email\">Email:</label>\r\n"
				+ "        <p id=\"email\">johndoe@example.com</p>\r\n"
				+ "    </div>\r\n"
				+ "    <div class=\"profile-info\">\r\n"
				+ "        <label for=\"phone\">Phone:</label>\r\n"
				+ "        <p id=\"phone\">123-456-7890</p>\r\n"
				+ "    </div>\r\n"
				+ "    <div class=\"btn-container\">\r\n"
				+ "        <button class=\"btn\" onclick=\"toggleEditProfile()\">Edit Profile</button>\r\n"
				+ "    </div>\r\n"
				+ "    <div class=\"edit-profile-form\">\r\n"
				+ "        <form>\r\n"
				+ "            <div class=\"profile-info\">\r\n"
				+ "                <label for=\"edit-username\">Username:</label>\r\n"
				+ "                <input type=\"text\" id=\"edit-username\" value=\"JohnDoe123\">\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"profile-info\">\r\n"
				+ "                <label for=\"edit-fullname\">Full Name:</label>\r\n"
				+ "                <input type=\"text\" id=\"edit-fullname\" value=\"John Doe\">\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"profile-info\">\r\n"
				+ "                <label for=\"edit-email\">Email:</label>\r\n"
				+ "                <input type=\"email\" id=\"edit-email\" value=\"johndoe@example.com\">\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"profile-info\">\r\n"
				+ "                <label for=\"edit-phone\">Phone:</label>\r\n"
				+ "                <input type=\"text\" id=\"edit-phone\" value=\"123-456-7890\">\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"btn-container\">\r\n"
				+ "                <button class=\"btn\" onclick=\"saveProfile()\">Save</button>\r\n"
				+ "                <button class=\"btn\" onclick=\"cancelEdit()\">Cancel</button>\r\n"
				+ "            </div>\r\n"
				+ "        </form>\r\n"
				+ "    </div>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "<script>\r\n"
				+ "    function toggleEditProfile() {\r\n"
				+ "        var profileInfo = document.getElementsByClassName(\"profile-info\");\r\n"
				+ "        var editProfileForm = document.getElementsByClassName(\"edit-profile-form\")[0];\r\n"
				+ "        var btnEditProfile = document.getElementsByClassName(\"btn\")[0];\r\n"
				+ "        \r\n"
				+ "        for (var i = 0; i < profileInfo.length; i++) {\r\n"
				+ "            profileInfo[i].style.display = \"none\";\r\n"
				+ "        }\r\n"
				+ "        \r\n"
				+ "        editProfileForm.style.display = \"block\";\r\n"
				+ "        btnEditProfile.style.display = \"none\";\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    function cancelEdit() {\r\n"
				+ "        var profileInfo = document.getElementsByClassName(\"profile-info\");\r\n"
				+ "        var editProfileForm = document.getElementsByClassName(\"edit-profile-form\")[0];\r\n"
				+ "        var btnEditProfile = document.getElementsByClassName(\"btn\")[0];\r\n"
				+ "\r\n"
				+ "        for (var i = 0; i < profileInfo.length; i++) {\r\n"
				+ "            profileInfo[i].style.display = \"block\";\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        editProfileForm.style.display = \"none\";\r\n"
				+ "        btnEditProfile.style.display = \"block\";\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    function saveProfile() {\r\n"
				+ "        var editUsername = document.getElementById(\"edit-username\").value;\r\n"
				+ "        var editFullname = document.getElementById(\"edit-fullname\").value;\r\n"
				+ "        var editEmail = document.getElementById(\"edit-email\").value;\r\n"
				+ "        var editPhone = document.getElementById(\"edit-phone\").value;\r\n"
				+ "\r\n"
				+ "        document.getElementById(\"username\").textContent = editUsername;\r\n"
				+ "        document.getElementById(\"fullname\").textContent = editFullname;\r\n"
				+ "        document.getElementById(\"email\").textContent = editEmail;\r\n"
				+ "        document.getElementById(\"phone\").textContent = editPhone;\r\n"
				+ "\r\n"
				+ "        cancelEdit();\r\n"
				+ "    }\r\n"
				+ "</script>\r\n"
				+ "\r\n"
				+ "</body>\r\n"
				+ "</html>\r\n" );
	}

}
